apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "showcase-chart.fullname" . }}-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showcase-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    deploymentConfig: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: keycloak
        deploymentConfig: keycloak
      name: keycloak
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: janus-idp
          image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
          livenessProbe:
            failureThreshold: 100
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          name: keycloak
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 300
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: empty
          args: ["start-dev"]
      volumes:
        - name: empty
          emptyDir: {}
  triggers:
    - type: ConfigChange
