apiVersion: v1
kind: Service
metadata:
  name: {{ include "showcase-chart.fullname" . }}-keycloak
spec:
  ports:
    - port: {{ .Values.keycloak.service.port}}
      targetPort: {{ .Values.keycloak.service.port }}
  selector:
    deploymentConfig: keycloak
