apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "test-chart.fullname" . }}-sonarqube
  namespace: {{ .Release.Namespace }}
spec:
  tags:
  - annotations:
      description: The SonarQube Docker image
      tags: sonarqube
    from:
      kind: DockerImage
      name: {{ .Values.sonarqube.imageStream.name }}
    importPolicy: {}
    name: {{ .Values.sonarqube.imageStream.tag }}
