apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-chart.fullname" . }}-sonarqube
  namespace: {{ .Release.namespace }}
spec:
  ports:
  - name: {{ include "test-chart.fullname" . }}-sonarqube
    port: {{ .Values.sonarqube.service.port }}
    protocol: TCP
    targetPort: {{ .Values.sonarqube.service.port }}
  selector:
    deploymentconfig: {{ include "test-chart.fullname" . }}-sonarqube
  sessionAffinity: None
  type: ClusterIP
