apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-ssl-certificate
spec:
  dnsNames:
    - son.apps.ci-ln-j5xqvkt-76ef8.aws-2.ci.openshift.org
  issuerRef:
    name: letsencrypt
  secretName: sonarqube-cert
