apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: "janus-idp" 
spec:
  tls:
    - hosts: 
      - son.apps.ci-ln-3bl270t-76ef8.origin-ci-int-aws.dev.rhcloud.com
      secretName: sonarqube-cert
  rules:
    - host: son.apps.ci-ln-3bl270t-76ef8.origin-ci-int-aws.dev.rhcloud.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sonarqube
                port:
                  number: 9000
