apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-certificate
spec:
  dnsNames:
    - show.apps.ci-ln-tzfgntb-76ef8.aws-2.ci.openshift.org
  issuerRef:
    name: letsencrypt
  secretName: janus-idp-cert
