apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: "janus-idp"
  labels:
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: janus-idp
spec:
  tls:
    - hosts:
      - showc.apps.ci-ln-3bl270t-76ef8.origin-ci-int-aws.dev.rhcloud.com
      secretName: janus-idp-cert
  rules:
    - host: show.apps.ci-ln-3bl270t-76ef8.origin-ci-int-aws.dev.rhcloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backstage
                port:
                  number: 7007
