# Production values for showcase-chart.

namespace: janus-idp-prod

# Janus Showcase
nameOverride: janus-showcase
fullnameOverride: janus-showcase-prod

## Certificate Values
dnsNames: 
  - showcase.janus-idp.io

## Deployment
replicas: 1

image:
  repository: quay.io/janus-idp/backstage-showcase
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 500m
  requests:
    cpu: 400m

oauth:
  name: oauth2-proxy
  enabled: false
  insecure: false
  cookieSecret: ""
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    pullPolicy: Always
    tag: "latest"
  resources:
    limits:
      cpu: 100m
    requests:
      cpu: 100m
  port: 4180

## Issuer
email: team-backstage@redhat.com

# Backstage
backstage:
  port: 7007
  baseUrl: showcase.janus-idp.io

# Keycloak
keycloak:
  dnsNames:
    - keycloak.apps.smaug.na.operate-first.ch

## DeploymentConfig
  replicas: 1

  image:
    repository: quay.io/keycloak/keycloak
    tag: 20.0.3

## Ingress
  baseUrl: keycloak.apps.smaug.na.operate-first.ch

## Service
  service:
    name: keycloak
    port: 8080

# Sonarqube
sonarqube:
  dnsNames:
    - sonar.apps.smaug.na.operate-first.cloud

## DeploymentConfig
  replicas: 1

  image:
    repository: 

## Ingress
  baseUrl: sonar.apps.smaug.na.operate-first.cloud

## Service
  service:
    name: sonarqube
    port: 9000