apiVersion: v1
kind: Service
metadata:
  name: {{ include "showcase-chart.fullname" . }}-sonarqube
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showcase-chart.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.sonarqube.service.name }}
    port: {{ .Values.sonarqube.service.port }}
    protocol: TCP
    targetPort: {{ .Values.sonarqube.service.port }}
  selector:
    deploymentconfig: sonarqube
  sessionAffinity: None
  type: ClusterIP
