apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "showcase-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showcase-chart.labels" . | nindent 4 }}
spec:
  tls:
    - hosts:
      - {{ .Values.backstage.baseUrl }}
      secretName: janus-idp-cert
  rules:
    - host: {{ .Values.backstage.baseUrl }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "showcase-chart.fullname" . }}
                port:
                  number: {{ .Values.oauth.enabled | ternary .Values.oauth.port .Values.backstage.port }}
