{{- if .Values.dnsNames }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.email }}
    privateKeySecretRef:
      name: letsencrypt-key
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
{{- end }}