apiVersion: v1
kind: Service
metadata:
  name: {{ include "showcase-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "showcase-chart.labels" . | nindent 4}}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-backend
      port: {{ .Values.oauth.enabled | ternary .Values.oauth.port .Values.backstage.port }}
      targetPort: {{ .Values.oauth.enabled | ternary .Values.oauth.name "backend" }}
      protocol: TCP
  selector:
    {{- include "showcase-chart.selectorLabels" . | nindent 4 }}
