global:
  host: show-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

backstage:
  upstream:
    commonLabels:
      backstage.io/kubernetes-id: janus-idp
    ingress:
      enabled: true
      tls:
        enabled: false
        secretName: janus-idp-cert
      host: show-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org
    backstage:
      extraEnvVarsSecrets:
        - janus-idp
        - janus-idp-showcase-pguser-janus-idp
      extraVolumes:
        - name: ca-cert
          secret:
            secretName: janus-idp-showcase-cluster-cert
            items:
              - key: ca.crt
                path: ca.crt
      extraVolumeMounts:
        - name: ca-cert
          mountPath: "/mnt/certs"
    postgresql:
      enabled: false
  route:
    enabled: false
    host: show-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org
    tls:
      enabled: false

## Showcase
showcase:
  issuer: 
    email: pknight@redhat.com
  tls:
    dnsNames:
      - show-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

## Keycloak
keycloak:
  enabled: true

  host: key-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

  tls:
    enabled: false
    secretName: keycloak-idp-cert
    dnsNames:
      - key-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

  service:
    name: keycloak
    port: 8080

  replicas: 1

  image:
    repository: quay.io/keycloak/keycloak
    tag: 20.0.3

## Sonarqube
sonarqube:
  enabled: true

  host: son-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

  tls:
    enabled: false
    secretName: sonar-idp-cert
    dnsNames:
      - son-dev.apps.ci-ln-r8b821k-76ef8.aws-2.ci.openshift.org

  service:
    name: sonarqube
    port: 9000
  
  replicas: 1

  imageStream:
    name: sonarqube:9.9-community
    tag: 9.9-community
