global:
  host: backstage.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

backstage:
  upstream:
    ingress:
      enabled: true
      tls:
        enabled: false
        secretName: janus-idp-cert
      host: backstage.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com
    backstage:
      extraEnvVarsSecrets:
        - janus-idp
        - showcase-test-chart-pguser-janus-idp
        - showcase-test-chart-bucket-claim
    postgresql:
      enabled: false
  route:
    enabled: false
    host: backstage.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com
    tls:
      enabled: false

# test:
#   - configMapRef:
#       name: {{ include "showcase-chart.fullname" . }}-bucket-claim

## Showcase
showcase:
  tls:
    dnsNames:
      - backstage.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

## Keycloak
keycloak:
  instances: 1
  realm:
    name: backstage
    enabled: true
    displayName: Backstage Authentication Realm
    identityProvider:
      enabled: false
      clientId: ""
      clientSecret: ""
  client:
    name: backstage

## Sonarqube
sonarqube:
  host: sonar.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

  tls:
    enabled: false
    secretName: sonar-idp-cert
    dnsNames:
      - sonar.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

  service:
    name: sonarqube
    port: 9000
  
  replicas: 1

  imageStream:
    name: sonarqube:9.9-community
    tag: 9.9-community
