global:
  host: show.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

backstage:
  upstream:
    commonLabels:
      backstage.io/kubernetes-id: janus-idp
    ingress:
      enabled: true
      tls:
        enabled: false
        secretName: janus-idp-cert
      host: show.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com
    backstage:
      extraEnvVarsSecrets:
        - janus-idp
        - janus-idp-showcase-pguser-janus-idp
      extraVolumes:
        - name: ca-cert
          secret:
            secretName: janus-idp-showcase-cluster-cert
            items:
              - key: ca.crt
                path: ca.crt
      extraVolumeMounts:
        - name: ca-cert
          mountPath: "/mnt/certs"
    postgresql:
      enabled: false
  route:
    enabled: false
    host: show.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com
    tls:
      enabled: false

## Showcase
showcase:
  issuer: 
    email: pknight@redhat.com
  tls:
    dnsNames:
      - show.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

## Keycloak
keycloak:
  host: key.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

  tls:
    enabled: false
    secretName: keycloak-idp-cert
    dnsNames:
      - key.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

  service:
    name: keycloak
    port: 8080

  replicas: 1

  image:
    repository: quay.io/keycloak/keycloak
    tag: 20.0.3

## Sonarqube
sonarqube:
  host: son.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

  tls:
    enabled: false
    secretName: sonar-idp-cert
    dnsNames:
      - son.apps.ci-ln-b2479zt-76ef8.origin-ci-int-aws.dev.rhcloud.com

  service:
    name: sonarqube
    port: 9000
  
  replicas: 1

  imageStream:
    name: sonarqube:9.9-community
    tag: 9.9-community
