global:
  host: back.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

backstage:
  upstream:
    ingress:
      enabled: true
      tls:
        enabled: true
        secretName: janus-idp-cert
      host: back.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com
    backstage:
      extraEnvVarsSecrets:
        - janus-idp
        - showcase-test-chart-pguser-janus-idp
      extraVolumes:
        - name: ca-cert
          secret:
            secretName: showcase-test-chart-cluster-cert
            items:
              - key: ca.crt
                path: ca.crt
      extraVolumeMounts:
        - name: ca-cert
          mountPath: "/mnt/certs"
    postgresql:
      enabled: false
  route:
    enabled: false
    host: back.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com
    tls:
      enabled: false

## Showcase
showcase:
  issuer: pknight@redhat.com
  tls:
    dnsNames:
      - back.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

## Keycloak
keycloak:
  instances: 1
  realm:
    name: backstage
    enabled: true
    displayName: Backstage Authentication Realm
    identityProvider:
      enabled: false
      clientId: ""
      clientSecret: ""
  client:
    name: backstage

## Sonarqube
sonarqube:
  host: son.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

  tls:
    enabled: true
    secretName: sonar-idp-cert
    dnsNames:
      - son.apps.ci-ln-wxsplik-76ef8.origin-ci-int-aws.dev.rhcloud.com

  service:
    name: sonarqube
    port: 9000
  
  replicas: 1

  imageStream:
    name: sonarqube:9.9-community
    tag: 9.9-community
