global:
  host: backstage.apps.example.com

backstage:
  upstream:
    ingress:
      enabled: true
      tls:
        enabled: false
        secretName: janus-idp-cert
      host: backstage.apps.example.com
  route:
    enabled: false
    host: backstage.apps.example.com
    tls:
      enabled: false

## Showcase
showcase:
  tls:
  dnsNames:
    - showcase.janus-idp.io

## Keycloak
keycloak:
  instances: 1
  realm:
    name: backstage
    enabled: true
    displayName: Backstage Authentication Realm
    identityProvider:
      enabled: false
      clientId: ""
      clientSecret: ""
  client:
    name: backstage

## Sonarqube
sonarqube:
  host: sonar.apps.smaug.na.operate-first.cloud

  tls:
    enabled: false
    secretName: sonar-idp-cert
    dnsNames:
    - sonar.apps.smaug.na.operate-first.cloud

  service:
    name: sonarqube
    port: 9000
  
  replicas: 1

  imageStream:
    name: sonarqube:9.9-community
    tag: 9.9-community

## Postgres
postgres:
  enabled: true
