apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ include "test-chart.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  externalAccess:
    enabled: true
