apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ .Values.keycloak.realm.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  realm:
    id: {{ .Values.keycloak.realm.name }}
    realm: {{ .Values.keycloak.realm.name }}
    enabled: {{ .Values.keycloak.realm.enabled }}
    displayName: {{ .Values.keycloak.realm.displayName }}
{{- if .Values.keycloak.realm.identityProvider.enabled }}
    identityProviders:
      - alias: github
        config:
          clientId: {{ required "GitHub Identity Provider Client ID must be provided" .Values.keycloak.realm.identityProvider.clientId }}
          clientSecret: {{ required "GitHub Identity Provider Client Secret must be provided" .Values.keycloak.realm.identityProvider.clientSecret }}
        trustEmail: true
        providerId: github
{{- end }}
  instanceSelector:
    matchLabels:
      {{- include "test-chart.selectorLabels" . | nindent 6 }}