apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .Values.keycloak.client.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  realmSelector:
    matchLabels:
      {{- include "test-chart.selectorLabels" . | nindent 6 }}
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
  client:
    clientId: {{ .Values.keycloak.client.name }}
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
      - roles
    consentRequired: false
    serviceAccountsEnabled: true
    redirectUris:
      - {{ required "Backstage host is required" (printf "https://%s/oauth2/callback" .Values.global.host) }}