{{- if .Values.keycloak.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "test-chart.fullname" . }}-keycloak
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  {{- with .Values.keycloak.tls.dnsNames }}
  dnsNames:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  issuerRef:
    name: letsencrypt
  secretName: {{ .Values.keycloak.tls.secretName }}
{{- end }}
