apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ include "test-chart.fullname" . }}-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.keycloak.replicas }}
  selector:
    deploymentconfig: {{ include "test-chart.fullname" . }}-keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentconfig: {{ include "test-chart.fullname" . }}-keycloak
      name: keycloak
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: janus-idp
          image: {{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 100
            httpGet:
              path: /
              port: {{ .Values.keycloak.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: keycloak
          ports:
            - containerPort: {{ .Values.keycloak.service.port }}
              protocol: TCP
          readinessProbe:
            failureThreshold: 300
            httpGet:
              path: /
              port: {{ .Values.keycloak.service.port }}
              scheme: HTTP
            initialDelaySeconds: 30
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: empty
          args: ["start-dev"]
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: '1'
              memory: 1Gi
      volumes:
        - name: empty
          emptyDir: {}
  triggers:
    - type: ConfigChange
