apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-certificate
spec:
  dnsNames:
    - key.apps.ci-ln-3bl270t-76ef8.origin-ci-int-aws.dev.rhcloud.com
  issuerRef:
    name: letsencrypt
  secretName: keycloak-cert
